const log = {
  config: {
    adapter: ["xhr", "http", "fetch"],
    allowAbsoluteUrls: true,
    data: undefined,
    env: { Blob: [], FormData: [Function] },
    headers: [Object],
    maxBodyLength: -1,
    maxContentLength: -1,
    method: "get",
    timeout: 0,
    transformRequest: [[Function]],
    transformResponse: [[Function]],
    transitional: {
      clarifyTimeoutError: false,
      forcedJSONParsing: true,
      silentJSONParsing: true,
    },
    url: "https://api.paystack.co/transaction/verify/T836405882828192",
    validateStatus: [Function],
    xsrfCookieName: "XSRF-TOKEN",
    xsrfHeaderName: "X-XSRF-TOKEN",
  },
  data: {
    data: {
      amount: 285412,
      authorization: [Object],
      channel: "card",
      connect: null,
      createdAt: "2025-05-27T12:38:27.000Z",
      created_at: "2025-05-27T12:38:27.000Z",
      currency: "NGN",
      customer: [Object],
      domain: "test",
      fees: 14282,
      fees_breakdown: null,
      fees_split: null,
      gateway_response: "Successful",
      id: 5004001122,
      ip_address: "102.88.110.87",
      log: [Object],
      message: null,
      metadata: [Object],
      order_id: null,
      paidAt: "2025-05-27T12:38:31.000Z",
      paid_at: "2025-05-27T12:38:31.000Z",
      plan: null,
      plan_object: [Object],
      pos_transaction_data: null,
      receipt_number: null,
      reference: "T836405882828192",
      requested_amount: 285412,
      source: null,
      split: [Object],
      status: "success",
      subaccount: [Object],
      transaction_date: "2025-05-27T12:38:27.000Z",
    },
    message: "Verification successful",
    status: true,
  },
  headers: {
    "access-control-allow-origin": "*",
    "cf-cache-status": "DYNAMIC",
    "cf-ray": "946591eb9e2a9421-LHR",
    "content-encoding": "gzip",
    "content-length": "830",
    "content-type": "application/json; charset=utf-8",
    date: "Tue, 27 May 2025 12:38:33 GMT",
    etag: 'W/"672-Py6GgkCHBO56BoaYRSi0aQ"',
    server: "cloudflare",
    "set-cookie": [Array],
    "strict-transport-security": "max-age=15552000; includeSubDomains; preload",
    vary: "Accept-Encoding",
    "x-amz-apigw-id": "LOjLjG6GjoEEX5Q=",
    "x-amzn-remapped-connection": "keep-alive",
    "x-amzn-remapped-date": "Tue, 27 May 2025 12:38:33 GMT",
    "x-amzn-remapped-server": "nginx",
    "x-amzn-requestid": "ccbc8067-1a9d-4f3c-be6e-75cc6d2c6cd9",
    "x-content-type-options": "nosniff",
    "x-ratelimit-limit": "120",
    "x-ratelimit-remaining": "120",
  },
  request: {
    DONE: 4,
    HEADERS_RECEIVED: 2,
    LOADING: 3,
    OPENED: 1,
    UNSENT: 0,
    _aborted: false,
    _cachedResponse: undefined,
    _hasError: false,
    _headers: {
      accept: "application/json, text/plain, */*",
      authorization: "Bearer sk_test_cbbccadee059e4afa47053d8806fd65b835f2476",
    },
    _incrementalEvents: false,
    _lowerCaseResponseHeaders: {
      "access-control-allow-origin": "*",
      "cf-cache-status": "DYNAMIC",
      "cf-ray": "946591eb9e2a9421-LHR",
      "content-encoding": "gzip",
      "content-length": "830",
      "content-type": "application/json; charset=utf-8",
      date: "Tue, 27 May 2025 12:38:33 GMT",
      etag: 'W/"672-Py6GgkCHBO56BoaYRSi0aQ"',
      server: "cloudflare",
      "set-cookie":
        "sails.sid=s%3AmDcGp8TP3ZrQv4Zz4PJxLSUqyCqyozQe.6ZjJjP1mC3XeXNH1mxUw6f7yTpaJnJSPnSwDbo9iEP8; Path=/; HttpOnly; Secure; SameSite=Lax, __cf_bm=dlXmWzxbhGsQ7AC4dCN5bvzR_sCRiiEXbImWrZEkW7k-1748349513-1.0.1.1-nujGazRdb4O33GR1sCa2npZUeivB7oE2.z6dtJLpNUzCjt.Se629hzVJWOZFOCtz_GlhjaHjuiPda7RM9jkxHZ81C2aRCJ8EiM0pSjyS1w0; path=/; expires=Tue, 27-May-25 13:08:33 GMT; domain=.paystack.co; HttpOnly; Secure; SameSite=None",
      "strict-transport-security":
        "max-age=15552000; includeSubDomains; preload",
      vary: "Accept-Encoding",
      "x-amz-apigw-id": "LOjLjG6GjoEEX5Q=",
      "x-amzn-remapped-connection": "keep-alive",
      "x-amzn-remapped-date": "Tue, 27 May 2025 12:38:33 GMT",
      "x-amzn-remapped-server": "nginx",
      "x-amzn-requestid": "ccbc8067-1a9d-4f3c-be6e-75cc6d2c6cd9",
      "x-content-type-options": "nosniff",
      "x-ratelimit-limit": "120",
      "x-ratelimit-remaining": "120",
    },
    _method: "GET",
    _perfKey:
      "network_XMLHttpRequest_https://api.paystack.co/transaction/verify/T836405882828192",
    _performanceLogger: {
      _closed: false,
      _extras: [Object],
      _pointExtras: [Object],
      _points: [Object],
      _timespans: [Object],
    },
    _requestId: null,
    _response:
      '{"status":true,"message":"Verification successful","data":{"id":5004001122,"domain":"test","status":"success","reference":"T836405882828192","receipt_number":null,"amount":285412,"message":null,"gateway_response":"Successful","paid_at":"2025-05-27T12:38:31.000Z","created_at":"2025-05-27T12:38:27.000Z","channel":"card","currency":"NGN","ip_address":"102.88.110.87","metadata":{"custom_fields":[{"display_name":"undefined undefined","variable_name":"undefined","value":""}],"referrer":"about:blank"},"log":{"start_time":1748349508,"time_spent":4,"attempts":1,"errors":0,"success":true,"mobile":true,"input":[],"history":[{"type":"action","message":"Attempted to pay with card","time":3},{"type":"success","message":"Successfully paid with card","time":4}]},"fees":14282,"fees_split":null,"authorization":{"authorization_code":"AUTH_jkhdehkk2x","bin":"408408","last4":"4081","exp_month":"12","exp_year":"2030","channel":"card","card_type":"visa ","bank":"TEST BANK","country_code":"NG","brand":"visa","reusable":true,"signature":"SIG_s7wA2O0sTlbPXaeTqONd","account_name":null,"receiver_bank_account_number":null,"receiver_bank":null},"customer":{"id":254692607,"first_name":"","last_name":"","email":"ezimorahtobenna@gmail.com","customer_code":"CUS_vh2xrz81k6jfvaa","phone":"","metadata":null,"risk_action":"default","international_format_phone":null},"plan":null,"split":{},"order_id":null,"paidAt":"2025-05-27T12:38:31.000Z","createdAt":"2025-05-27T12:38:27.000Z","requested_amount":285412,"pos_transaction_data":null,"source":null,"fees_breakdown":null,"connect":null,"transaction_date":"2025-05-27T12:38:27.000Z","plan_object":{},"subaccount":{}}}',
    _responseType: "",
    _sent: true,
    _startTime: 2306533872.105791,
    _subscriptions: [],
    _timedOut: false,
    _trackingName: null,
    _url: "https://api.paystack.co/transaction/verify/T836405882828192",
    readyState: 4,
    responseHeaders: {
      "Access-Control-Allow-Origin": "*",
      "Content-Encoding": "gzip",
      "Content-Length": "830",
      "Content-Type": "application/json; charset=utf-8",
      Date: "Tue, 27 May 2025 12:38:33 GMT",
      Etag: 'W/"672-Py6GgkCHBO56BoaYRSi0aQ"',
      Server: "cloudflare",
      "Set-Cookie":
        "sails.sid=s%3AmDcGp8TP3ZrQv4Zz4PJxLSUqyCqyozQe.6ZjJjP1mC3XeXNH1mxUw6f7yTpaJnJSPnSwDbo9iEP8; Path=/; HttpOnly; Secure; SameSite=Lax, __cf_bm=dlXmWzxbhGsQ7AC4dCN5bvzR_sCRiiEXbImWrZEkW7k-1748349513-1.0.1.1-nujGazRdb4O33GR1sCa2npZUeivB7oE2.z6dtJLpNUzCjt.Se629hzVJWOZFOCtz_GlhjaHjuiPda7RM9jkxHZ81C2aRCJ8EiM0pSjyS1w0; path=/; expires=Tue, 27-May-25 13:08:33 GMT; domain=.paystack.co; HttpOnly; Secure; SameSite=None",
      "Strict-Transport-Security":
        "max-age=15552000; includeSubDomains; preload",
      Vary: "Accept-Encoding",
      "cf-cache-status": "DYNAMIC",
      "cf-ray": "946591eb9e2a9421-LHR",
      "x-amz-apigw-id": "LOjLjG6GjoEEX5Q=",
      "x-amzn-remapped-connection": "keep-alive",
      "x-amzn-remapped-date": "Tue, 27 May 2025 12:38:33 GMT",
      "x-amzn-remapped-server": "nginx",
      "x-amzn-requestid": "ccbc8067-1a9d-4f3c-be6e-75cc6d2c6cd9",
      "x-content-type-options": "nosniff",
      "x-ratelimit-limit": "120",
      "x-ratelimit-remaining": "120",
    },
    responseURL: "https://api.paystack.co/transaction/verify/T836405882828192",
    status: 200,
    timeout: 0,
    upload: {},
    withCredentials: true,
  },
  status: 200,
  statusText: undefined,
};
